### ISSUE TITLE
Incorrect Inferred relationship are generating.

### ISSUE THREAD

**Issue by dhirendraps** [IHTSDO/classification-service#1]
Hi @kaicode , I am successfully able to create a new concept on the given branch but at the time of classification of that concept it prompt that classification completed successfully and when i check the classification results it show's status as added but source, type  and destination as null. I already imported the previous release file archive on the branch in termserver and all the MRCM rules.

I am attaching the screenshot of my browser showing classification results. Please help in understating what i am missing in authoring process.
![screenshot 51](https://user-images.githubusercontent.com/43638925/51182834-6dd15400-18f5-11e9-9ff8-e2c32dab64b4.png)

**Comment by kaicode** [comment]
Hi @dhirendraps, please attach a screenshot of the JSON response from the API. The API response should include just concept ids. It's the responsibility of the frontend to lookup the terms to display against the classification results. Do you have any javascript errors?

**Comment by dhirendraps** [comment]
list of relationship changes responses are there after the Rest Api call "https://snomed-authoring.mig.in/snowowl/snomed-ct/v2/MAIN/CMP/CMP-2/classifications/35ebaeff-3f73-4a42-825c-c89c77290087/relationship-changes?expand=source.fsn,type.fsn,destination.fsn&limit=1000"

JSON Response:

{"items":[
			{"changeNature":"INFERRED","sourceId":"31000003106","sourceFsn":"Product containing precisely paracetamol 350 mg oral tablet (clinical drug)","typeId":"116680003","typeFsn":"Is a (attribute)","destinationId":"437876006","destinationFsn":"Product containing paracetamol in oral dosage form (medicinal product form)","destinationNegated":false,"characteristicTypeId":"900000000000011006","group":0,"unionGroup":0,"modifier":"EXISTENTIAL"},
			{"changeNature":"INFERRED","sourceId":"31000003106","sourceFsn":"Product containing precisely paracetamol 350 mg oral tablet (clinical drug)","typeId":"127489000","typeFsn":"Has active ingredient (attribute)","destinationId":"387517004","destinationFsn":"Paracetamol (substance)","destinationNegated":false,"characteristicTypeId":"900000000000011006","group":0,"unionGroup":0,"modifier":"EXISTENTIAL"},
			{"changeNature":"INFERRED","sourceId":"31000003106","sourceFsn":"Product containing precisely paracetamol 350 mg oral tablet (clinical drug)","typeId":"411116001","typeFsn":"Has manufactured dose form (attribute)","destinationId":"421026006","destinationFsn":"Conventional release oral tablet (dose form)","destinationNegated":false,"characteristicTypeId":"900000000000011006","group":0,"unionGroup":0,"modifier":"EXISTENTIAL"},
			{"changeNature":"INFERRED","sourceId":"425630003","sourceFsn":"Acute irritant contact dermatitis (disorder)","typeId":"42752001","typeFsn":"Due to (attribute)","destinationId":"400195000","destinationFsn":"Contact hypersensitivity reaction (disorder)","destinationNegated":false,"characteristicTypeId":"900000000000011006","group":0,"unionGroup":0,"modifier":"EXISTENTIAL"},
			{"changeNature":"INFERRED","sourceId":"425630003","sourceFsn":"Acute irritant contact dermatitis (disorder)","typeId":"116680003","typeFsn":"Is a (attribute)","destinationId":"111189002","destinationFsn":"Acute contact dermatitis (disorder)","destinationNegated":false,"characteristicTypeId":"900000000000011006","group":0,"unionGroup":0,"modifier":"EXISTENTIAL"},
			{"changeNature":"INFERRED","sourceId":"425630003","sourceFsn":"Acute irritant contact dermatitis (disorder)","typeId":"246075003","typeFsn":"Causative agent (attribute)","destinationId":"105590001","destinationFsn":"Substance (substance)","destinationNegated":false,"characteristicTypeId":"900000000000011006","group":0,"unionGroup":0,"modifier":"EXISTENTIAL"}
			
		],"offset":0,"limit":1000,"total":6		
}

And there is a javascript errors on console "Cannot read property 'id' of undefined"
![screenshot 52](https://user-images.githubusercontent.com/43638925/51184859-8b092100-18fb-11e9-99cd-80b4c18685d9.png)

**Comment by kaicode** [comment]
Okay. The Classification Service API has returned the concept identifiers and the Snow Owl API has added the terms. The JavaScript error may mean you are using a version of the frontend Authoring UI which is not compatible with this backend. 

Which version of Snow Owl and Authoring UI are you basing your implementation on?

**Comment by dhirendraps** [comment]
I am using Snow Owl version -5.10.18 and Authoring-UI verison-2.8.2 and All Other services version according to "Authoring Platform Version 2.7.2 - 30 November 2017 - Release Notes".

**Comment by kaicode** [comment]
Snow Owl version 5.10.18 was deployed in the Snomed International Authoring Platform against Authoring UI version 2.7.7 in [Authoring Platform Version 2.7.2](https://confluence.ihtsdotools.org/display/AUTHS/Authoring+Platform+Version+2.7.2+-+30+November+2017+-+Release+Notes)

Authoring UI version 2.8.2 which you have could be used with Snow Owl version 5.11.4 as was deployed in [Authoring Platform Version 2.8.0](https://confluence.ihtsdotools.org/display/AUTHS/Authoring+Platform+Version+2.8.0+-+25+January+2018+-+Release+Notes)

I expect this is the root cause of the problem you are seeing. You are likely to find other incompatibilities between the versions you have deployed as your testing progresses. I suggest upgrading Snow Owl.

Wishing you the best. Kai

**Comment by dhirendraps** [comment]
Hi @kaicode, I am using Authoring-Ui version 2.7.7 with Snow Owl version 5.10.18 and other services accoring to the Authoring Platform Version 2.7.2 but still javascript error "Cannot read property 'id' of undefined" is coming . Please provide a benchmark for the services which we can use for specific release.

**Comment by kaicode** [comment]
The issue you are having seems to be in integration issue between the Snow Owl and Authoring UI. I can confirm that we did use these versions together in production so the issue you are seeing is unexpected.

You have a couple options to resolve this: 
- Try deploying the components from a later version of the Authoring Platform.
- or Debug the issue using the Authoring UI source code from that release.

These are open source projects which are provided as is with no support for specific deployments. I can tell you what versions of the components worked for Snomed International in production and give you pointers but that is all. You may need a frontend developer with some Angular knowledge to help you with this. 

I hope you get this working.

Kind regards,
Kai
