### ISSUE TITLE
Missing dockerization and public images

### ISSUE THREAD

**Issue by akszydelko** [IHTSDO/classification-service#14]
There are few related issues:
- Unlike other other services/repositories (e.g. Snowstorm or Browser), the Classification Service does not have have docker setup, the Dockerfile nor docker compose file. 
- There are also docker images in public registry (at least that I can find).
- Also the repository releases are not up to date, so there is no easy way to get ready to use jar file.

Having those things in place would be very useful, in the company I work for we are experimenting with SNOMED CT Extension and Classification Service is a crucial component. We had to build our own pipeline to build the image for internal use.

Are there any plans to add the dockerization and maintain public images?

P.S. I can help with the docker setup in the repository if you wish, which is half the job, but I'm afraid docker image publication is out of reach for me (unless I'm mistaken)

**Comment by CoderMChu** [comment]
@akszydelko Thanks for raising this. Yes it would be great if you can make a pull request for the dockerization changes and then we can add the publication part using jib-maven-plugin.

**Comment by akszydelko** [comment]
Hey @CoderMChu I have added a simple Dockerfile to build and run the project. Let me know if it is ok or of if there is anything more I can do ;)

I have seen you removed Dockerfile from snowstorm repo and I started to wonder what is your building process, maybe to keep the container building scripts in different place and the Dockerfile is not needed here after all. I was trying to make it similar to Dockerfile that I found in snowstorm-x repository.

**Comment by CoderMChu** [comment]
@akszydelko Thanks for adding the Dockerfile. Sorry for the late reply as I was on holiday. Yes snowstorm repo uses jib-maven-plugin which doesn't require Dockerfile. I have updated classification-serivce to use jib as well. Local testing looks good and I have pushed a docker image in docker hub.  You can check via link https://hub.docker.com/repository/docker/snomedinternational/classification-service/general

**Comment by CoderMChu** [comment]
@akszydelko You can find changes committed in develop branch. Any issues please let me know. Thanks.

**Comment by akszydelko** [comment]
No worries, I was also on holiday 🌴 actually 😄. I will test the new images soon and get back with the feedback, but I don't suspect there will be any issue. Thanks a lot for pushing it the images to registry already!

**Comment by akszydelko** [comment]
@CoderMChu It took some time, but I can confirm that the image you pushed to Docker Hub (https://hub.docker.com/r/snomedinternational/classification-service/tags) is working as expected 🙏.

But if I'm not mistaken the image pushed to the registry does not have the change discussed in the other thread: https://github.com/IHTSDO/classification-service/pull/15#discussion_r1592437239. If I remember correctly you prepared the dockerization and pushed the image to Docker Hub registry. Then we discussed the extra parameters and you only added the changes to develop branch without pushing new image. So it would be great to have the images with the latest changes pushed to the registry ;)

Anyway if the flow is all done on your side and updates to classification service will result in new image versions, I think we can close the issue. I will also close my PR https://github.com/IHTSDO/classification-service/pull/15 as it is not relevant anymore.

**Comment by CoderMChu** [comment]
@akszydelko  Thanks for confirming. Those jvm configs are already pushed to master for 9.2.0 release. https://github.com/IHTSDO/classification-service/blob/master/pom.xml#L317

If you use the latest or 9.2.0 docker image, it should have these. I will close this issue. Thanks.
