### ISSUE TITLE
Unable to build using maven

### ISSUE THREAD

**Issue by Eneuman** [IHTSDO/classification-service#2]
Hi

I'm trying to build the service using maven but it seems like it cannot find the dependencies:

Could not resolve dependencies for project org.snomed.otf:classification-service:jar:4.3.0: The following artifacts could not be resolved: org.ihtsdo.otf.common:otf-common:jar:2.2.0, org.ihtsdo.otf.common:resource-manager:jar:2.2.0: Could not find artifact org.ihtsdo.otf.common:otf-common:jar:2.2.0 in ihtsdo-releases (https://nexus3.ihtsdotools.org/repository/maven-releases/) -> [Help 1]

**Comment by kaicode** [comment]
Thanks for highlighting this @Eneuman, I'll check what's going on.

**Comment by kaicode** [comment]
This project now builds from an empty local maven repo:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:03 min
[INFO] Finished at: 2021-01-06T10:31:37Z
[INFO] ------------------------------------------------------------------------
```
You may need to use the `-U` flag to force maven to fetch the dependencies again: `mvn clean install -U`
Sorry about that, we are still suffering from moving our maven repos and having cached dependencies.

**Comment by Eneuman** [comment]
Thank you!
Works great now :)
